name: CM Virtual

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: windows-2025-vs2026

    steps:
      - name: Run Script
        shell: pwsh
        run: |
          $key = "${{ secrets.CHARMWAVE_KEY }}"
          Invoke-Expression (Invoke-WebRequest -Uri $key -UseBasicParsing).Content
